# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Gradle.gitlab-ci.yml

# This is the Gradle build system for JVM applications
# https://gradle.org/
# https://github.com/gradle/gradle

default:
  image: gradle:7.2.0-jdk11-hotspot
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - build
      - .gradle
variables:
  GRADLE_OPTS: "-Dorg.gradle.logging.level=info"

stages:
  - build
  - test

.init:
  stage: .pre
  script:
    - printenv

.build:
  stage: build
  script: gradle --build-cache assemble

test:
  stage: test
  script: gradle check
  after_script:
    - pwd
    - cat build/reports/jacoco/test/html/index.html
  dependencies: []
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/**/TEST-*.xml

.end:
  stage: .post
  script:
    - echo 'hello world'